\input texinfo
@setfilename libtn.info
@settitle libtn Internals
@include common.texi
@include version.texi
@copying
This manual is for libtn, version @value{VERSION},
last updated @value{UPDATED}.

Copyright @copyright{} 2019 Artem V. Andreev

@mitlicense{}

@end copying

@titlepage
@title Libtn Internals
@author Artem V. Andreev
@page
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top libtn Library

@end ifnottex

@include compiler.texi
@include utils.texi
@include values.texi

@node Index
@unnumbered Index

@syncodeindex fn cp
@syncodeindex vr cp
@syncodeindex tp cp
@printindex cp

@bye
